defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: nsgaii

param_group:
  x: 10
  y: -5

wandb:
  project: sweep-test
  entity: yp-edu
  mode: offline

hydra:
  sweeper:
    sampler:
      seed: 0
    direction: minimize
    n_trials: 20
    n_jobs: 5
    params:
      param_group.x: range(-10, 10, 0.5)
      param_group.y: range(-10, 10, 0.5)
  sweep:
    dir: results/hydra/${hydra.job.name}-run/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: results/hydra/${hydra.job.name}-sweep/${now:%Y-%m-%d_%H-%M-%S}
