name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    matrix:
      python-version:
        - "3.11"
        - "3.12"
    environment: ci
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync --python ${{ matrix.python-version }} --locked
    - name: Run checks
      run: |
        make checks
    - name: Download assets
      run: |
        make test-assets
    - name: Run tests
      run: |
        make tests
