name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-python-3_11:
    runs-on: ubuntu-latest
    environment: ci
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync --python 3.11 --locked
    - name: Run checks
      run: |
        make checks
    - name: Download assets
      run: |
        make test-assets
    - name: Run tests
      run: |
        make tests
